-- Run once in Supabase SQL Editor. No personally identifiable information is stored.
create table if not exists public.weko_analytics_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null check (
    event_type in ('visit', 'survey_start', 'answer', 'survey_complete', 'result_view', 'share')
  ),
  visitor_id text not null,
  visit_id text not null,
  question_id text,
  answer_value text,
  result_type text,
  share_channel text,
  source text,
  medium text,
  campaign text,
  traffic_source text check (
    traffic_source is null or traffic_source in ('Instagram', 'Kakao', 'Direct', 'Other')
  ),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists weko_analytics_event_type_time_idx
  on public.weko_analytics_events (event_type, occurred_at desc);
create index if not exists weko_analytics_visitor_idx
  on public.weko_analytics_events (visitor_id, occurred_at desc);
create index if not exists weko_analytics_visit_idx
  on public.weko_analytics_events (visit_id, occurred_at desc);
create index if not exists weko_analytics_question_idx
  on public.weko_analytics_events (question_id, occurred_at desc)
  where question_id is not null;

alter table public.weko_analytics_events enable row level security;
revoke all on table public.weko_analytics_events from anon, authenticated;
revoke all on sequence public.weko_analytics_events_id_seq from anon, authenticated;

comment on table public.weko_analytics_events is
  'Anonymous WENK survey, acquisition and sharing events. Accessed only by the Flask backend service role.';
